### ISSUE TITLE
Graph: Time to acceptance

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/dashboard#11]
For packages closed as accepted, within a given time period, what is the total time from submittal to closed?  How has this changed over time?  Are there bad times of year?

How to visualize?
 - Average or median value for everything in that quarter?
 - Some visualization of the distribution in that quarter?
 - Is quarter the useful period?
 - Separate for categories (regular/stats)?

**Comment by mpadge** [comment]
- [x] Average or median value for everything in that quarter?
- [ ] Some visualization of the distribution in that quarter?
- [x] Is quarter the useful period? - yes, quarter is best, with a small amount of smoothing
- [x] Separate for categories (regular/stats)? - done

@noamross This is now all done, except that there is no visualisation of distribution within quarters. I think the current visualisation shows all the information we need, without showing distributions within quarters. If you agree, please close, or otherwise comment here. Thanks.

**Comment by mpadge** [comment]
@noamross Are you satisfied with https://ropensci-review-tools.github.io/dashboard/history.html#review-duration? Anything else you'd like to see there, or any changes to current form? Note that variances of review durations don't reveal anything useful; just a general correlation with mean values as expected for a Poisson-type process.
