### ISSUE TITLE
past activity

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/dashboard#17]
This makes it look as if Emily only ever handled one submission?

![image](https://github.com/ropensci-review-tools/dashboard/assets/8360597/6d2bb166-1c66-4b26-936d-a7cd3dc3154c)

**Comment by mpadge** [comment]
Interesting. That's an inadvertent side-effect of the way the data are displayed. An alternative version at https://github.com/ropensci-review-tools/dashboard/issues/8#issuecomment-2009943734 makes her contributions a bit clearer. More generally, I'll close this issue because it'll be addressed by #8 one way or another anyway. Thanks!
